site_name: Carte
repo_url: https://github.com/carte-data/carte-frontend
repo_name: carte-data/carte-frontend
site_url: https://cartedata.com
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
    accent: teal
  features:
    - search.highlight
    - search.suggest
    - navigation.sections
docs_dir: content
plugins:
  - search:
      separator: '[\s\-\.\_]+'
      lang: en
markdown_extensions:
  - meta
  - attr_list
extra_css:
  - stylesheets/extra.css
edit_uri: ""
